### ISSUE TITLE
PDF ファイルのリンクが切れている

### ISSUE THREAD

**Issue by kyanny** [azu/promises-book#229]
http://azu.github.io/promises-book/javascript-promise-book.pdf この URL ですが、現在 PDF ファイルをダウンロードできないようです。

**Comment by azu** [comment]
@kyanny ありがとうございます。修正します。。 :soon:

**Comment by azu** [comment]
@kyanny PDFの生成に失敗してたのが原因だったので修正しました。ご報告ありがとうございます。
再発防止用にpdfが生成されてるかのチェックを入れます。

**Comment by kyanny** [comment]
@azu PDF ダウンロードできました。ありがとうございます :bowtie:
