### ISSUE TITLE
I doubt that this is not a mini book on Promise.

### ISSUE THREAD

**Issue by miniroadrunner** [azu/promises-book#282]
This mini book is not mini, it takes too long pages to describe the Promise, the new feature in ES6.

**Comment by azu** [comment]
> JavaScript Promiseについての薄い電子書籍です。

We hadn't said mini.

Duplicate of #280

**Comment by miniroadrunner** [comment]
yes? I am Chinese. I read your book in Chinese Edition (Chinese: JavaScript Promise迷你书（中文版）). And the Chinese "迷你" in English is mini. Why name this book "迷你书" in Chinese ?
