### ISSUE TITLE
Fulfilled と FulFilled の表記ゆれ

### ISSUE THREAD

**Issue by oohira** [azu/promises-book#349]
[CONTRIBUTING.md](https://github.com/azu/promises-book/blob/master/CONTRIBUTING.md#resolvereject--fulfilledrejected-%E3%81%AE%E8%A1%A8%E7%8F%BE) にも書いてあるので意図的なような気もしますが、正しくは「Fulfilled」ではないでしょうか。一括置換してしまってよいものか判断できなかったので、ひとまずIssueだけ挙げさせていただきます。

```shell
$ grep -r "Fulfilled" . | wc -l                       
     173

$ grep -r "FulFilled" . | wc -l
      44
```

**Comment by oohira** [comment]
大事なことを言い忘れました。説明がとても分かりやすくて素晴らしいです。執筆ありがとうございます！

**Comment by azu** [comment]
おそらくただの表記ゆれな気がするので、統一していいと思います。

**Comment by oohira** [comment]
`./archives/v1/` 以下にも該当箇所があるのですが、こちらは当時のスナップショットとして触らずに残しておいた方がよいでしょうか？

```shell
$ grep -r "FulFilled" archives/v1 | wc -l
      19
```

**Comment by azu** [comment]
意味的な違いはないので、一緒に置換してしまって問題ないと思います。
