### ISSUE TITLE
Promise Anti-patterns へのリンクを開くとリンク広告のようなページが表示される

### ISSUE THREAD

**Issue by hankei6km** [azu/promises-book#363]
URL : https://azu.github.io/promises-book/#then-return-new-promise

https://github.com/azu/promises-book/blob/42d97bd199aad446a0bc6f44377d76cd5eab1854/Ch2_HowToWrite/then-return-new-promise.adoc?plain=1#L109

上記行の下に記述されているリンクを開くとリンク広告のようなページが表示されます。
詳しい状況はわからないのですがリンク先は更新されていないのかもしれません。

**Comment by azu** [comment]
ありがとうございます。
リンク先がなくっていそうですね。
とりあえずアーカイブに変更しました
https://web.archive.org/web/20211219034053/http://taoofcode.net/promise-anti-patterns/

**Comment by hankei6km** [comment]
ご対応ありがとうございます。
内容の確認ができました。
