### ISSUE TITLE
Web版右上の "Fork me on GitHub" のリボン画像が画像切れしている

### ISSUE THREAD

**Issue by nsfisis** [azu/promises-book#368]
https://azu.github.io/promises-book/ において、右上の "Fork me on GitHub" のリボン画像が画像切れしています。

<img width="704" alt="image" src="https://github.com/user-attachments/assets/79564c28-7033-494c-881f-2dbe3e7fa2ff">

`img` タグに設定されている `src` (`https://camo.githubusercontent.com/38ef81f8aca64bb9a64448d0d70f1308ef5341ab/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f6461726b626c75655f3132313632312e706e67`) に直接アクセスすると、403 になっています。

現時点における GitHub 公式の HTML は https://github.blog/news-insights/the-library/github-ribbons/ で提供されているようです。

> ```html
> <a href="https://github.com/you"><img decoding="async" width="149" height="149" src="https://github.blog/wp-content/uploads/2008/12/forkme_right_darkblue_121621.png" class="attachment-full size-full" alt="Fork me on GitHub" loading="lazy"></a>
> ```

**Comment by azu** [comment]
ありがとうございます #369 で修正しました
